# Generated by Django 5.2.7 on 2026-06-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artista_options_and_more'),
        ('creations', '0004_alter_arte_options_alter_colecao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arte',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AddIndex(
            model_name='arte',
            index=models.Index(fields=['artista', 'ativa'], name='creations_a_artista_e5fa5d_idx'),
        ),
        migrations.AddIndex(
            model_name='arte',
            index=models.Index(fields=['colecao', 'ativa'], name='creations_a_colecao_9fd27e_idx'),
        ),
        migrations.AddIndex(
            model_name='arte',
            index=models.Index(fields=['criado_em'], name='creations_a_criado__949d7b_idx'),
        ),
    ]
